name: Build YimMenu

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild YimMenu.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: YimMenu.dll
          path: bin/x64/Release/YimMenu.dll
